# -*- coding: utf-8 -*-
"""Q3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2OiZKx9SCzFDTXlKWEDC_pDZ1zgfb7N
"""

import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))
print("VRAM:", round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2), "GB")

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Zheng-Chong/CatVTON.git
# %cd /content/CatVTON

!ls

import os

catvton_path = "/root/.cache/huggingface/hub/models--zhengchong--CatVTON/snapshots/2969fcf85fe62f2036605716f0b56f0b81d01d79"

for root, dirs, files in os.walk(catvton_path):
    level = root.replace(catvton_path, "").count(os.sep)
    if level <= 2:
        print("  " * level + os.path.basename(root) + "/")
        for f in files[:10]:
            print("  " * (level + 1) + f)

import numpy
import torch

print("NumPy:", numpy.__version__)
print("PyTorch:", torch.__version__)
print("CUDA:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

import diffusers
import transformers
import accelerate

print("Diffusers:", diffusers.__version__)
print("Transformers:", transformers.__version__)
print("Accelerate:", accelerate.__version__)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/CatVTON

!pwd
!ls model

!pip install -q "accelerate==1.2.1"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/CatVTON

import numpy
import torch
import diffusers
import transformers
import accelerate

print("NumPy:", numpy.__version__)
print("PyTorch:", torch.__version__)
print("Diffusers:", diffusers.__version__)
print("Transformers:", transformers.__version__)
print("Accelerate:", accelerate.__version__)
print("CUDA:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

from model.pipeline import CatVTONPipeline

print("✅ CatVTON import successful")

import numpy
import torch
import diffusers
import transformers
import accelerate

print("NumPy:", numpy.__version__)
print("PyTorch:", torch.__version__)
print("Diffusers:", diffusers.__version__)
print("Transformers:", transformers.__version__)
print("Accelerate:", accelerate.__version__)
print("CUDA:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

from model.pipeline import CatVTONPipeline

print("✅ CatVTON import successful")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/CatVTON

import torch
from model.pipeline import CatVTONPipeline

BASE_MODEL = "booksforcharlie/stable-diffusion-inpainting"

CATVTON_CHECKPOINT = (
    "/root/.cache/huggingface/hub/models--zhengchong--CatVTON/"
    "snapshots/2969fcf85fe62f2036605716f0b56f0b81d01d79"
)

pipe = CatVTONPipeline(
    base_ckpt=BASE_MODEL,
    attn_ckpt=CATVTON_CHECKPOINT,
    attn_ckpt_version="mix",
    weight_dtype=torch.float16,
    device="cuda",
    compile=False,
    skip_safety_check=True,
    use_tf32=True,
)

print("✅ CatVTON pipeline loaded successfully")

from google.colab import files

uploaded = files.upload()

print("Uploaded files:", list(uploaded.keys()))

!ls -lh /content/sample_files.zip

!unzip -q /content/sample_files.zip -d /content/xapien_q2_inputs
!find /content/xapien_q2_inputs/sample_files -maxdepth 2 -type f | head -30

import os

Q3_DIR = "/content/q3_outputs"
AGNOSTIC_DIR = os.path.join(Q3_DIR, "agnostic")
GARMENT_MASK_DIR = os.path.join(Q3_DIR, "garment_masks")
RESULT_DIR = os.path.join(Q3_DIR, "tryon_results")

for d in [Q3_DIR, AGNOSTIC_DIR, GARMENT_MASK_DIR, RESULT_DIR]:
    os.makedirs(d, exist_ok=True)

print("Q3 directories ready:")
print(Q3_DIR)
print(AGNOSTIC_DIR)
print(GARMENT_MASK_DIR)
print(RESULT_DIR)

from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection

DINO_MODEL_ID = "IDEA-Research/grounding-dino-base"

dino_processor = AutoProcessor.from_pretrained(DINO_MODEL_ID)
dino_model = AutoModelForZeroShotObjectDetection.from_pretrained(
    DINO_MODEL_ID
).to(device)

dino_model.eval()

print("✅ Grounding DINO loaded")

from transformers import SamProcessor, SamModel

SAM_MODEL_ID = "facebook/sam-vit-base"

sam_processor = SamProcessor.from_pretrained(SAM_MODEL_ID)

sam_model = SamModel.from_pretrained(
    SAM_MODEL_ID
).to(device)

sam_model.eval()

print("✅ SAM loaded")

import os
import numpy as np
import torch
from PIL import Image
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

PERSON_PATH = "/content/xapien_q2_inputs/sample_files/test_pairs/person/person_01.png"

AGNOSTIC_PATH = "/content/q3_outputs/agnostic/person_01.png"
PARSING_PATH = "/content/q3_outputs/parsing_person_01.png"

os.makedirs("/content/q3_outputs/agnostic", exist_ok=True)

# ------------------------------------------------------------
# SAME CLASS DEFINITIONS FROM YOUR Q2
# ------------------------------------------------------------

CLASS_IDS = {
    "background": 0,
    "hair": 1,
    "face": 2,
    "upper_clothing": 3,
    "left_arm": 4,
    "right_arm": 5,
    "lower_body": 6
}

priority = [
    ("lower_body", CLASS_IDS["lower_body"]),
    ("upper_clothing", CLASS_IDS["upper_clothing"]),
    ("left_arm", CLASS_IDS["left_arm"]),
    ("right_arm", CLASS_IDS["right_arm"]),
    ("face", CLASS_IDS["face"]),
    ("hair", CLASS_IDS["hair"])
]

semantic_candidates = {
    "face": ["face"],
    "hair": ["hair"],
    "left_arm": ["left arm", "arm"],
    "right_arm": ["right arm", "arm"],
    "lower_body": [
        "pants", "trousers", "skirt",
        "shorts", "jeans", "legs"
    ],
    "upper_clothing": [
        "shirt", "t-shirt", "t shirt",
        "top", "blouse", "dress", "jacket"
    ]
}

dino_labels = [
    "face", "hair",
    "left arm", "right arm",
    "pants", "trousers", "skirt",
    "shorts", "jeans", "legs",
    "shirt", "t-shirt", "top",
    "blouse", "dress", "jacket"
]

text_prompt = ". ".join(dino_labels) + "."

CONF_THRESHOLDS_TO_TRY = [0.25, 0.15, 0.10]

# ------------------------------------------------------------
# LOAD PERSON
# ------------------------------------------------------------

image = Image.open(PERSON_PATH).convert("RGB")

print("Processing:", PERSON_PATH)
print("Image size:", image.size)

# ------------------------------------------------------------
# WHOLE PERSON — GROUNDING DINO
# ------------------------------------------------------------

person_inputs = dino_processor(
    images=image,
    text="person.",
    return_tensors="pt"
)

person_inputs = {
    k: v.to(device) if hasattr(v, "to") else v
    for k, v in person_inputs.items()
}

with torch.no_grad():
    person_outputs = dino_model(**person_inputs)

person_results = dino_processor.post_process_grounded_object_detection(
    person_outputs,
    person_inputs["input_ids"],
    target_sizes=[image.size[::-1]]
)[0]

if len(person_results["boxes"]) == 0:
    raise RuntimeError("No person detected.")

best_person_idx = int(torch.argmax(person_results["scores"]))

person_box = (
    person_results["boxes"][best_person_idx]
    .detach()
    .cpu()
    .tolist()
)

person_score = float(
    person_results["scores"][best_person_idx]
)

print(
    f"Person box: {person_box} "
    f"(score={person_score:.3f})"
)

# ------------------------------------------------------------
# PERSON MASK — SAM
# ------------------------------------------------------------

sam_person_input = sam_processor(
    images=image,
    input_boxes=[[person_box]],
    return_tensors="pt"
)

sam_person_input = {
    k: v.to(device) if hasattr(v, "to") else v
    for k, v in sam_person_input.items()
}

with torch.no_grad():
    sam_person_output = sam_model(**sam_person_input)

person_masks_processed = (
    sam_processor.image_processor.post_process_masks(
        sam_person_output.pred_masks.cpu(),
        sam_person_input["original_sizes"].cpu(),
        sam_person_input["reshaped_input_sizes"].cpu()
    )
)

person_mask = (
    person_masks_processed[0][0][0]
    .numpy()
    .astype(bool)
)

print(
    "Person mask pixels:",
    int(person_mask.sum())
)

# ------------------------------------------------------------
# BODY-PART / CLOTHING DETECTIONS
# SAME THRESHOLD RETRY FROM YOUR Q2
# ------------------------------------------------------------

boxes = []
scores = []
filtered_labels = []

for conf_threshold in CONF_THRESHOLDS_TO_TRY:

    inputs = dino_processor(
        images=image,
        text=text_prompt,
        return_tensors="pt"
    )

    inputs = {
        k: v.to(device) if hasattr(v, "to") else v
        for k, v in inputs.items()
    }

    with torch.no_grad():
        outputs = dino_model(**inputs)

    results = dino_processor.post_process_grounded_object_detection(
        outputs,
        inputs["input_ids"],
        target_sizes=[image.size[::-1]]
    )[0]

    detected_labels = results.get("text_labels", None)

    if detected_labels is None:
        detected_labels = [
            str(l)
            for l in results.get("labels", [])
        ]

    keep = [
        i
        for i, s in enumerate(results["scores"])
        if float(s) >= conf_threshold
    ]

    if keep:
        boxes = [results["boxes"][i] for i in keep]
        scores = [results["scores"][i] for i in keep]
        filtered_labels = [
            detected_labels[i]
            for i in keep
        ]

        print(
            f"✅ Detections at "
            f"threshold={conf_threshold}: "
            f"{len(boxes)}"
        )

        break

    else:
        print(
            f"⚠️ No detections at "
            f"threshold={conf_threshold}, "
            f"retrying lower..."
        )

# ------------------------------------------------------------
# PRINT DETECTIONS
# ------------------------------------------------------------

for i in range(len(boxes)):

    print(
        f"  {filtered_labels[i]:15s} "
        f"score={float(scores[i]):.3f} "
        f"box={[round(x,1) for x in boxes[i].detach().cpu().tolist()]}"
    )

# ------------------------------------------------------------
# SEMANTIC MASKS VIA SAM
# ------------------------------------------------------------

semantic_masks = {}

for semantic_class, candidate_labels in semantic_candidates.items():

    candidate_indices = []

    for i, detected_label in enumerate(filtered_labels):

        detected_lower = (
            str(detected_label)
            .lower()
            .strip()
        )

        for candidate in candidate_labels:

            candidate_lower = (
                candidate.lower()
                .strip()
            )

            if (
                detected_lower == candidate_lower
                or candidate_lower in detected_lower
                or detected_lower in candidate_lower
            ):
                candidate_indices.append(i)
                break

    candidate_indices = list(
        dict.fromkeys(candidate_indices)
    )

    if not candidate_indices:
        print(
            f"  ⚠️ No detection for "
            f"{semantic_class}"
        )
        continue

    best_idx = max(
        candidate_indices,
        key=lambda i: float(scores[i])
    )

    box = (
        boxes[best_idx]
        .detach()
        .cpu()
        .tolist()
    )

    best_score = float(scores[best_idx])

    sam_input = sam_processor(
        images=image,
        input_boxes=[[box]],
        return_tensors="pt"
    )

    sam_input = {
        k: v.to(device) if hasattr(v, "to") else v
        for k, v in sam_input.items()
    }

    with torch.no_grad():
        sam_output = sam_model(**sam_input)

    processed_masks = (
        sam_processor.image_processor.post_process_masks(
            sam_output.pred_masks.cpu(),
            sam_input["original_sizes"].cpu(),
            sam_input["reshaped_input_sizes"].cpu()
        )
    )

    mask = (
        processed_masks[0][0][0]
        .numpy()
        .astype(bool)
    )

    semantic_masks[semantic_class] = mask

    print(
        f"  ✅ {semantic_class:15s} "
        f"score={best_score:.3f} "
        f"pixels={int(mask.sum()):,}"
    )

# ------------------------------------------------------------
# PARSING MAP
# ------------------------------------------------------------

clean_masks = {
    name: mask & person_mask
    for name, mask in semantic_masks.items()
}

parsing_map = np.zeros(
    person_mask.shape,
    dtype=np.uint8
)

for name, class_id in priority:

    if name in clean_masks:
        parsing_map[clean_masks[name]] = class_id

Image.fromarray(parsing_map).save(
    PARSING_PATH
)

print("Parsing map saved:", PARSING_PATH)

# ------------------------------------------------------------
# AGNOSTIC IMAGE
# SAME METHOD FROM YOUR Q2
# ------------------------------------------------------------

image_array = np.array(image).copy()

clothing_mask = (
    parsing_map ==
    CLASS_IDS["upper_clothing"]
)

print(
    "Upper clothing pixels:",
    int(clothing_mask.sum())
)

agnostic = image_array.copy()

agnostic[clothing_mask] = [
    128, 128, 128
]

Image.fromarray(agnostic).save(
    AGNOSTIC_PATH
)

print("Agnostic saved:", AGNOSTIC_PATH)

# ------------------------------------------------------------
# VISUAL CHECK
# ------------------------------------------------------------

fig, axes = plt.subplots(
    1, 3,
    figsize=(15, 6)
)

axes[0].imshow(image)
axes[0].set_title("Original")
axes[0].axis("off")

axes[1].imshow(
    parsing_map,
    cmap="tab10",
    vmin=0,
    vmax=len(CLASS_IDS)-1
)
axes[1].set_title("Parsing Map")
axes[1].axis("off")

axes[2].imshow(agnostic)
axes[2].set_title("Agnostic")
axes[2].axis("off")

plt.suptitle(
    "person_01.png",
    fontsize=14
)

plt.tight_layout()
plt.show()

from transformers import SamProcessor, SamModel

SAM_MODEL = "facebook/sam-vit-base"

sam_processor = SamProcessor.from_pretrained(SAM_MODEL)
sam_model = SamModel.from_pretrained(SAM_MODEL).to(device)
sam_model.eval()

print("✅ SAM loaded")
print("SAM device:", next(sam_model.parameters()).device)

import os
from PIL import Image

PERSON_DIR = "/content/xapien_q2_inputs/sample_files/test_pairs/person"
GARMENT_DIR = "/content/xapien_q2_inputs/sample_files/test_pairs/garment"

Q3_DIR = "/content/q3_outputs"
AGNOSTIC_DIR = os.path.join(Q3_DIR, "agnostic")
GARMENT_MASK_DIR = os.path.join(Q3_DIR, "garment_masks")
TRYON_DIR = os.path.join(Q3_DIR, "tryon_results")

os.makedirs(AGNOSTIC_DIR, exist_ok=True)
os.makedirs(GARMENT_MASK_DIR, exist_ok=True)
os.makedirs(TRYON_DIR, exist_ok=True)

print("Person:", os.listdir(PERSON_DIR))
print("Garments:", os.listdir(GARMENT_DIR))
print("Q3 directories ready")

# ============================================================
# Q3 — USE THE SAME Q2 SEMANTIC DEFINITIONS
# ============================================================

CLASS_IDS = {
    "background": 0,
    "hair": 1,
    "face": 2,
    "upper_clothing": 3,
    "left_arm": 4,
    "right_arm": 5,
    "lower_body": 6
}

priority = [
    ("lower_body", CLASS_IDS["lower_body"]),
    ("upper_clothing", CLASS_IDS["upper_clothing"]),
    ("left_arm", CLASS_IDS["left_arm"]),
    ("right_arm", CLASS_IDS["right_arm"]),
    ("face", CLASS_IDS["face"]),
    ("hair", CLASS_IDS["hair"])
]

semantic_candidates = {
    "face": ["face"],
    "hair": ["hair"],
    "left_arm": ["left arm", "arm"],
    "right_arm": ["right arm", "arm"],
    "lower_body": ["pants", "trousers", "skirt", "shorts", "jeans", "legs"],
    "upper_clothing": ["shirt", "t-shirt", "t shirt", "top", "blouse", "dress", "jacket"]
}

dino_labels = [
    "face", "hair", "left arm", "right arm",
    "pants", "trousers", "skirt", "shorts", "jeans", "legs",
    "shirt", "t-shirt", "top", "blouse", "dress", "jacket"
]

text_prompt = ". ".join(dino_labels) + "."

CONF_THRESHOLDS_TO_TRY = [0.25, 0.15, 0.10]

print("✅ Q2 semantic configuration loaded")
print("Classes:", CLASS_IDS)
print("Thresholds:", CONF_THRESHOLDS_TO_TRY)

# ============================================================
# Q3 — GENERATE AGNOSTIC PERSON IMAGES
# SAME METHOD AS Q2
# ============================================================

import numpy as np
import torch
from PIL import Image

all_semantic_masks = {}
all_semantic_scores = {}

person_files = sorted([
    f for f in os.listdir(PERSON_DIR)
    if f.lower().endswith((".png", ".jpg", ".jpeg"))
])

for filename in person_files:

    print("\n" + "=" * 70)
    print("PROCESSING:", filename)
    print("=" * 70)

    image_path = os.path.join(PERSON_DIR, filename)
    image = Image.open(image_path).convert("RGB")

    # --------------------------------------------------------
    # Whole-person detection
    # --------------------------------------------------------

    person_inputs = dino_processor(
        images=image,
        text="person.",
        return_tensors="pt"
    )

    person_inputs = {
        k: v.to(device) if hasattr(v, "to") else v
        for k, v in person_inputs.items()
    }

    with torch.no_grad():
        person_outputs = dino_model(**person_inputs)

    person_results = dino_processor.post_process_grounded_object_detection(
        person_outputs,
        person_inputs["input_ids"],
        target_sizes=[image.size[::-1]]
    )[0]

    if len(person_results["boxes"]) == 0:
        print("❌ No person detected — skipping")
        continue

    best_person_idx = int(torch.argmax(person_results["scores"]))

    person_box = (
        person_results["boxes"][best_person_idx]
        .detach()
        .cpu()
        .tolist()
    )

    print(
        f"Person box: {person_box} "
        f"(score={float(person_results['scores'][best_person_idx]):.3f})"
    )

    # --------------------------------------------------------
    # SAM whole-person mask
    # --------------------------------------------------------

    sam_person_input = sam_processor(
        images=image,
        input_boxes=[[person_box]],
        return_tensors="pt"
    )

    sam_person_input = {
        k: v.to(device) if hasattr(v, "to") else v
        for k, v in sam_person_input.items()
    }

    with torch.no_grad():
        sam_person_output = sam_model(**sam_person_input)

    person_masks_processed = (
        sam_processor.image_processor.post_process_masks(
            sam_person_output.pred_masks.cpu(),
            sam_person_input["original_sizes"].cpu(),
            sam_person_input["reshaped_input_sizes"].cpu()
        )
    )

    person_mask = (
        person_masks_processed[0][0][0]
        .numpy()
        .astype(bool)
    )

    # --------------------------------------------------------
    # Body-part / clothing detection
    # SAME Q2 thresholds
    # --------------------------------------------------------

    boxes = []
    scores = []
    filtered_labels = []

    for conf_threshold in CONF_THRESHOLDS_TO_TRY:

        inputs = dino_processor(
            images=image,
            text=text_prompt,
            return_tensors="pt"
        )

        inputs = {
            k: v.to(device) if hasattr(v, "to") else v
            for k, v in inputs.items()
        }

        with torch.no_grad():
            outputs = dino_model(**inputs)

        results = dino_processor.post_process_grounded_object_detection(
            outputs,
            inputs["input_ids"],
            target_sizes=[image.size[::-1]]
        )[0]

        detected_labels = results.get("text_labels", None)

        if detected_labels is None:
            detected_labels = [
                str(l) for l in results.get("labels", [])
            ]

        keep = [
            i for i, s in enumerate(results["scores"])
            if float(s) >= conf_threshold
        ]

        if keep:
            boxes = [results["boxes"][i] for i in keep]
            scores = [results["scores"][i] for i in keep]
            filtered_labels = [detected_labels[i] for i in keep]

            print(
                f"✅ Detections at threshold={conf_threshold}: "
                f"{len(boxes)}"
            )
            break

        else:
            print(
                f"⚠️ No detections at threshold={conf_threshold}, "
                "retrying lower..."
            )

    # --------------------------------------------------------
    # Semantic masks through SAM
    # --------------------------------------------------------

    semantic_masks = {}
    semantic_scores = {}

    for semantic_class, candidate_labels in semantic_candidates.items():

        candidate_indices = []

        for i, detected_label in enumerate(filtered_labels):

            detected_lower = str(
                detected_label
            ).lower().strip()

            for candidate in candidate_labels:

                candidate_lower = candidate.lower().strip()

                if (
                    detected_lower == candidate_lower
                    or candidate_lower in detected_lower
                    or detected_lower in candidate_lower
                ):
                    candidate_indices.append(i)
                    break

        candidate_indices = list(dict.fromkeys(candidate_indices))

        if not candidate_indices:
            print(f"  ⚠️ No detection for {semantic_class}")
            continue

        best_idx = max(
            candidate_indices,
            key=lambda i: float(scores[i])
        )

        box = (
            boxes[best_idx]
            .detach()
            .cpu()
            .tolist()
        )

        best_score = float(scores[best_idx])

        sam_input = sam_processor(
            images=image,
            input_boxes=[[box]],
            return_tensors="pt"
        )

        sam_input = {
            k: v.to(device) if hasattr(v, "to") else v
            for k, v in sam_input.items()
        }

        with torch.no_grad():
            sam_output = sam_model(**sam_input)

        processed_masks = (
            sam_processor.image_processor.post_process_masks(
                sam_output.pred_masks.cpu(),
                sam_input["original_sizes"].cpu(),
                sam_input["reshaped_input_sizes"].cpu()
            )
        )

        mask = (
            processed_masks[0][0][0]
            .numpy()
            .astype(bool)
        )

        semantic_masks[semantic_class] = mask
        semantic_scores[semantic_class] = best_score

        print(
            f"  ✅ {semantic_class:15s} "
            f"score={best_score:.3f} "
            f"pixels={int(mask.sum()):,}"
        )

    # --------------------------------------------------------
    # Build parsing map
    # --------------------------------------------------------

    clean_masks = {
        name: (mask & person_mask)
        for name, mask in semantic_masks.items()
    }

    parsing_map = np.zeros(
        person_mask.shape,
        dtype=np.uint8
    )

    for name, class_id in priority:

        if name in clean_masks:
            parsing_map[clean_masks[name]] = class_id

    # --------------------------------------------------------
    # Agnostic representation
    # SAME Q2 METHOD
    # --------------------------------------------------------

    image_array = np.array(image).copy()

    clothing_mask = (
        parsing_map == CLASS_IDS["upper_clothing"]
    )

    agnostic = image_array.copy()

    agnostic[clothing_mask] = [128, 128, 128]

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    output_name = os.path.splitext(filename)[0] + ".png"

    agnostic_path = os.path.join(
        AGNOSTIC_DIR,
        output_name
    )

    Image.fromarray(agnostic).save(agnostic_path)

    all_semantic_masks[filename] = semantic_masks
    all_semantic_scores[filename] = semantic_scores

    print("✅ Agnostic saved:", agnostic_path)

print("\n" + "=" * 70)
print("Q3 AGNOSTIC PREPROCESSING COMPLETE")
print("=" * 70)

print(
    "Files:",
    sorted(os.listdir(AGNOSTIC_DIR))
)

# ============================================================
# Q3 — GARMENT MASKS
# Grounding DINO + SAM
# ============================================================

GARMENT_OUTPUT_DIR = GARMENT_MASK_DIR

garment_files = sorted([
    f for f in os.listdir(GARMENT_DIR)
    if f.lower().endswith((".png", ".jpg", ".jpeg"))
])

for filename in garment_files:

    print("\n" + "=" * 70)
    print("PROCESSING GARMENT:", filename)
    print("=" * 70)

    garment_path = os.path.join(GARMENT_DIR, filename)
    garment = Image.open(garment_path).convert("RGB")

    # --------------------------------------------------------
    # Detect garment
    # --------------------------------------------------------

    garment_inputs = dino_processor(
        images=garment,
        text="shirt. t-shirt. top. blouse. dress. jacket. garment.",
        return_tensors="pt"
    )

    garment_inputs = {
        k: v.to(device) if hasattr(v, "to") else v
        for k, v in garment_inputs.items()
    }

    with torch.no_grad():
        garment_outputs = dino_model(**garment_inputs)

    garment_results = dino_processor.post_process_grounded_object_detection(
        garment_outputs,
        garment_inputs["input_ids"],
        target_sizes=[garment.size[::-1]]
    )[0]

    if len(garment_results["boxes"]) == 0:
        print("❌ No garment detected")
        continue

    best_idx = int(torch.argmax(garment_results["scores"]))

    garment_box = (
        garment_results["boxes"][best_idx]
        .detach()
        .cpu()
        .tolist()
    )

    garment_score = float(
        garment_results["scores"][best_idx]
    )

    print(
        f"Garment box: {garment_box} "
        f"(score={garment_score:.3f})"
    )

    # --------------------------------------------------------
    # Segment detected garment with SAM
    # --------------------------------------------------------

    sam_input = sam_processor(
        images=garment,
        input_boxes=[[garment_box]],
        return_tensors="pt"
    )

    sam_input = {
        k: v.to(device) if hasattr(v, "to") else v
        for k, v in sam_input.items()
    }

    with torch.no_grad():
        sam_output = sam_model(**sam_input)

    processed_masks = (
        sam_processor.image_processor.post_process_masks(
            sam_output.pred_masks.cpu(),
            sam_input["original_sizes"].cpu(),
            sam_input["reshaped_input_sizes"].cpu()
        )
    )

    garment_mask = (
        processed_masks[0][0][0]
        .numpy()
        .astype(np.uint8)
    )

    # --------------------------------------------------------
    # Save binary mask
    # --------------------------------------------------------

    mask_image = Image.fromarray(
        garment_mask * 255
    )

    output_name = (
        os.path.splitext(filename)[0] + ".png"
    )

    output_path = os.path.join(
        GARMENT_OUTPUT_DIR,
        output_name
    )

    mask_image.save(output_path)

    print(
        f"✅ Garment mask saved: {output_path}"
    )

    print(
        f"Mask pixels: {int(garment_mask.sum()):,}"
    )

print("\n" + "=" * 70)
print("GARMENT MASK GENERATION COMPLETE")
print("=" * 70)

print(
    "Files:",
    sorted(os.listdir(GARMENT_OUTPUT_DIR))
)

# ============================================================
# Q3 — CATVTON TEST: PAIR 01
# ============================================================

import os
import torch
from PIL import Image

PERSON_01 = "/content/xapien_q2_inputs/sample_files/test_pairs/person/person_01.png"
GARMENT_01 = "/content/xapien_q2_inputs/sample_files/test_pairs/garment/garment_01.jpg"
MASK_01 = "/content/q3_outputs/agnostic/person_01.png"

person_img = Image.open(PERSON_01).convert("RGB")
garment_img = Image.open(GARMENT_01).convert("RGB")
mask_img = Image.open(MASK_01).convert("L")

print("Person:", person_img.size)
print("Garment:", garment_img.size)
print("Agnostic mask:", mask_img.size)

# Clear unused GPU memory
torch.cuda.empty_cache()

print(
    "GPU memory allocated:",
    round(torch.cuda.memory_allocated() / 1024**3, 2),
    "GB"
)
print(
    "GPU memory reserved:",
    round(torch.cuda.memory_reserved() / 1024**3, 2),
    "GB"
)

# ============================================================
# Q3 — PREPARE PAIR 01 FOR CATVTON
# Uses the Q2 agnostic image directly
# Derives the clothing mask from the gray pixels
# ============================================================

import numpy as np
from PIL import Image

# Load Q2-derived agnostic image
agnostic_img = Image.open(
    "/content/q3_outputs/agnostic/person_01.png"
).convert("RGB")

# Convert to numpy
agnostic_np = np.array(agnostic_img)

# Q2 replaced upper clothing with [128, 128, 128]
# Recover that exact clothing region
clothing_mask_np = np.all(
    agnostic_np == [128, 128, 128],
    axis=2
)

# Convert to binary PIL mask
clothing_mask = Image.fromarray(
    (clothing_mask_np.astype(np.uint8) * 255)
)

# Load garment
garment_img = Image.open(
    "/content/xapien_q2_inputs/sample_files/test_pairs/garment/garment_01.jpg"
).convert("RGB")

print("Agnostic:", agnostic_img.size)
print("Mask:", clothing_mask.size)
print("Garment:", garment_img.size)
print("Masked pixels:", int(clothing_mask_np.sum()))

# Save mask for verification
pair01_mask_path = "/content/q3_outputs/garment_masks/person_01_clothing_mask.png"
clothing_mask.save(pair01_mask_path)

print("✅ Pair 01 clothing mask saved:")
print(pair01_mask_path)

# ============================================================
# Q3 — CATVTON PAIR 01 INFERENCE
# ============================================================

import torch
import os
from PIL import Image

torch.cuda.empty_cache()

# ------------------------------------------------------------
# Inputs
# ------------------------------------------------------------

person = Image.open(
    "/content/q3_outputs/agnostic/person_01.png"
).convert("RGB")

garment = Image.open(
    "/content/xapien_q2_inputs/sample_files/test_pairs/garment/garment_01.jpg"
).convert("RGB")

mask = Image.open(
    "/content/q3_outputs/garment_masks/person_01_clothing_mask.png"
).convert("L")

# ------------------------------------------------------------
# Resize to T4-friendly resolution
# ------------------------------------------------------------

WIDTH = 384
HEIGHT = 512

print(f"Running CatVTON at {WIDTH}x{HEIGHT}")

# ------------------------------------------------------------
# Inference
# ------------------------------------------------------------

with torch.inference_mode():

    result = pipe(
        image=person,
        condition_image=garment,
        mask=mask,
        num_inference_steps=30,
        guidance_scale=2.5,
        height=HEIGHT,
        width=WIDTH,
    )

# ------------------------------------------------------------
# Save result
# ------------------------------------------------------------

output_path = "/content/q3_outputs/tryon_results/pair_01.png"

result[0].save(output_path)

print("✅ CatVTON inference completed")
print("✅ Output:", output_path)

print(
    "GPU allocated:",
    round(torch.cuda.memory_allocated() / 1024**3, 2),
    "GB"
)

# ============================================================
# Q3 — VISUAL CHECK PAIR 01
# ============================================================

import matplotlib.pyplot as plt
from PIL import Image

person_original = Image.open(
    "/content/xapien_q2_inputs/sample_files/test_pairs/person/person_01.png"
).convert("RGB")

garment = Image.open(
    "/content/xapien_q2_inputs/sample_files/test_pairs/garment/garment_01.jpg"
).convert("RGB")

agnostic = Image.open(
    "/content/q3_outputs/agnostic/person_01.png"
).convert("RGB")

result = Image.open(
    "/content/q3_outputs/tryon_results/pair_01.png"
).convert("RGB")

fig, axes = plt.subplots(1, 4, figsize=(16, 6))

axes[0].imshow(person_original)
axes[0].set_title("Original Person")
axes[0].axis("off")

axes[1].imshow(garment)
axes[1].set_title("Garment")
axes[1].axis("off")

axes[2].imshow(agnostic)
axes[2].set_title("Q2 Agnostic")
axes[2].axis("off")

axes[3].imshow(result)
axes[3].set_title("CatVTON Result")
axes[3].axis("off")

plt.tight_layout()
plt.show()

import os
from PIL import Image

AGNOSTIC_DIR = "/content/q3_outputs/agnostic"
MASK_DIR = "/content/q3_outputs/garment_masks"

for i in range(1, 6):
    person = f"person_{i:02d}.png"
    mask = f"person_{i:02d}_clothing_mask.png"

    agnostic_path = os.path.join(AGNOSTIC_DIR, person)
    mask_path = os.path.join(MASK_DIR, mask)

    print(f"{person}:", "Agnostic exists =", os.path.exists(agnostic_path),
          "| Clothing mask exists =", os.path.exists(mask_path))

import os
from PIL import Image

PERSON_DIR = "/content/xapien_q2_inputs/sample_files/test_pairs/person"
GARMENT_DIR = "/content/xapien_q2_inputs/sample_files/test_pairs/garment"
MASK_DIR = "/content/q3_outputs/garment_masks"
AGNOSTIC_DIR = "/content/q3_outputs/agnostic"
OUTPUT_DIR = "/content/q3_outputs/tryon_results"

for i in range(1, 6):

    person_name = f"person_{i:02d}.png"
    garment_name = f"garment_{i:02d}.jpg"
    output_name = f"pair_{i:02d}.png"

    person_path = os.path.join(PERSON_DIR, person_name)
    garment_path = os.path.join(GARMENT_DIR, garment_name)
    mask_path = os.path.join(MASK_DIR, f"person_{i:02d}_clothing_mask.png")
    output_path = os.path.join(OUTPUT_DIR, output_name)

    if os.path.exists(output_path):
        print(f"Already exists: {output_path}")
        continue

    person = Image.open(person_path).convert("RGB")
    garment = Image.open(garment_path).convert("RGB")
    mask = Image.open(mask_path).convert("L")

    print("=" * 60)
    print(f"Running CatVTON Pair {i:02d}")
    print("Person:", person.size)
    print("Garment:", garment.size)
    print("Mask:", mask.size)

    result = pipe(
        image=person,
        condition_image=garment,
        mask=mask,
        num_inference_steps=30,
        guidance_scale=2.5,
        height=512,
        width=384,
    )[0]

    result.save(output_path)

    print(f"✅ Pair {i:02d} completed")
    print(f"✅ Output: {output_path}")

import os
import matplotlib.pyplot as plt
from PIL import Image

PERSON_DIR = "/content/xapien_q2_inputs/sample_files/test_pairs/person"
GARMENT_DIR = "/content/xapien_q2_inputs/sample_files/test_pairs/garment"
AGNOSTIC_DIR = "/content/q3_outputs/agnostic"
MASK_DIR = "/content/q3_outputs/garment_masks"
RESULT_DIR = "/content/q3_outputs/tryon_results"

fig, axes = plt.subplots(5, 5, figsize=(18, 25))

for i in range(1, 6):

    person = Image.open(
        os.path.join(PERSON_DIR, f"person_{i:02d}.png")
    ).convert("RGB")

    garment = Image.open(
        os.path.join(GARMENT_DIR, f"garment_{i:02d}.jpg")
    ).convert("RGB")

    agnostic = Image.open(
        os.path.join(AGNOSTIC_DIR, f"person_{i:02d}.png")
    ).convert("RGB")

    mask = Image.open(
        os.path.join(MASK_DIR, f"person_{i:02d}_clothing_mask.png")
    ).convert("L")

    result = Image.open(
        os.path.join(RESULT_DIR, f"pair_{i:02d}.png")
    ).convert("RGB")

    images = [person, garment, agnostic, mask, result]
    titles = [
        f"Person {i:02d}",
        f"Garment {i:02d}",
        "Agnostic",
        "Clothing Mask",
        "CatVTON Result"
    ]

    for j, (img, title) in enumerate(zip(images, titles)):
        axes[i-1, j].imshow(img)
        axes[i-1, j].set_title(title, fontsize=11)
        axes[i-1, j].axis("off")

plt.suptitle(
    "Q3 — Virtual Try-On Results",
    fontsize=20,
    fontweight="bold"
)

plt.tight_layout()
plt.show()

import os
import shutil

# ============================================================
# Q3 — FINAL 5 TRY-ON IMAGES ONLY
# ============================================================

RESULT_DIR = "/content/q3_outputs/tryon_results"
SUBMISSION_DIR = "/content/Q3_final_outputs"
ZIP_BASE = "/content/Q3_final_outputs"

# Clean previous package
if os.path.exists(SUBMISSION_DIR):
    shutil.rmtree(SUBMISSION_DIR)

if os.path.exists(ZIP_BASE + ".zip"):
    os.remove(ZIP_BASE + ".zip")

os.makedirs(SUBMISSION_DIR)

# Copy ONLY the 5 official pair outputs
for i in range(1, 6):
    filename = f"pair_{i:02d}.png"
    source = os.path.join(RESULT_DIR, filename)
    destination = os.path.join(SUBMISSION_DIR, filename)

    if os.path.exists(source):
        shutil.copy2(source, destination)
        print("✅ Copied:", filename)
    else:
        print("❌ Missing:", filename)

# Create ZIP
shutil.make_archive(
    ZIP_BASE,
    "zip",
    SUBMISSION_DIR
)

print("\n✅ FINAL Q3 PACKAGE READY")
print("Folder:", SUBMISSION_DIR)
print("ZIP:", ZIP_BASE + ".zip")

from google.colab import files

files.download("/content/Q3_final_outputs.zip")

